In [123]:
# 공통 및 정의
import numpy as np
import pandas as pd
import os
from numpy.random import randn
os.chdir("/home/piai/Desktop/git/1 Big Data 분석 기초")

## 실습 1번

In [124]:
#Step1
dict_data = {'1':"홍길동", '2':"이순신", '3':"강감찬"}
sr = pd.Series(dict_data)
print(type(sr))
display(sr)

<class 'pandas.core.series.Series'>

1    홍길동
2    이순신
3    강감찬
dtype: object

In [125]:
#Step2
table = {"성명" : ["홍길동", "이순신", "강감찬", "이성계", "정약용"],
         "국어성적" :[90,95,85,90,95],
         "영어성적" :[90,85,90,95,95],
         "수학성적" :[95,90,85,75,90]}
df = pd.DataFrame(table)
display(df)

    성명  국어성적  영어성적  수학성적
0  홍길동    90    90    95
1  이순신    95    85    90
2  강감찬    85    90    85
3  이성계    90    95    75
4  정약용    95    95    90

## 실습 2번

In [126]:
#Step1
df = pd.read_csv('성적.csv', encoding = 'cp949', index_col = 0)

In [127]:
#Step2
display(df)
df.to_csv('성적사본.csv', encoding = 'cp949', index = False)

    성명  국어성적  영어성적  수학성적
0  홍길동    90    90    95
1  이순신    95    85    90
2  강감찬    85    90    85
3  이성계    90    95    75
4  정약용    95    95    90

## 실습 3번

In [128]:
#Step1
df = pd.read_csv('FITNESS.csv', encoding = 'cp949')

In [129]:
#Step2
display(df.head())

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185

In [130]:
#Step3
display(df.describe())

,AGE,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,46.838710,77.444516,47.375806,10.586129,169.645161,53.451613,173.774194
std,5.860016,8.328568,5.327231,1.387414,10.251986,7.619443,9.164095
min,37.000000,59.080000,37.388000,8.170000,146.000000,40.000000,155.000000
25%,43.000000,73.200000,44.964500,9.780000,163.000000,48.000000,168.000000
50%,48.000000,77.450000,46.774000,10.470000,170.000000,52.000000,172.000000
75%,51.000000,82.325000,50.131000,11.270000,176.000000,58.500000,180.000000
max,57.000000,91.630000,60.055000,14.030000,186.000000,70.000000,192.000000

In [131]:
#Step4
df1 = df.select_dtypes('number')
df1['GENDER'] = df['GENDER']
display(df1.groupby(by = 'GENDER').agg(['mean', 'median']))

#구버전
display(df.groupby(by = 'GENDER').agg(['mean', 'median']))

              AGE            WEIGHT               OXY            RUNTIME  \
             mean median       mean median       mean   median      mean
GENDER
남성      46.333333   45.0  82.282667  81.42  44.753733  45.3130  11.19400
여성      47.312500   48.5  72.908750  73.54  49.834000  48.2965  10.01625

              RUNPULSE          RSTPULSE        MAXPULSE
       median     mean median       mean median     mean median
GENDER
남성      10.95   172.20  174.0  55.733333   57.0  175.800  176.0
여성      10.04   167.25  168.0  51.312500   48.0  171.875  170.0

/tmp/ipykernel_169571/1719932269.py:7: FutureWarning: ['NAME', 'AGEGROUP'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  display(df.groupby(by = 'GENDER').agg(['mean', 'median']))

              AGE            WEIGHT               OXY            RUNTIME  \
             mean median       mean median       mean   median      mean
GENDER
남성      46.333333   45.0  82.282667  81.42  44.753733  45.3130  11.19400
여성      47.312500   48.5  72.908750  73.54  49.834000  48.2965  10.01625

              RUNPULSE          RSTPULSE        MAXPULSE
       median     mean median       mean median     mean median
GENDER
남성      10.95   172.20  174.0  55.733333   57.0  175.800  176.0
여성      10.04   167.25  168.0  51.312500   48.0  171.875  170.0

## 실습 4번

In [132]:
#Step1
np.random.seed(1234)
df = pd.DataFrame(randn(10,4),columns = ['A','B','C','D'])

In [133]:
#Step2
#1
display(df[['B']])
#2
display(df[['B','D']])
#3
display(df[4:9])

          B
0 -1.190976
1  0.887163
2 -2.242685
3 -2.021255
4  0.289092
5 -0.655969
6 -0.469305
7  1.058969
8  1.045938
9 -0.322795

          B         D
0 -1.190976 -0.312652
1  0.887163 -0.636524
2 -2.242685  0.991946
3 -2.021255  0.002118
4  0.289092 -1.546906
5 -0.655969  0.553439
6 -0.469305 -1.817027
7  1.058969  0.337438
8  1.045938 -0.122092
9 -0.322795  2.390961

          A         B         C         D
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [134]:
#Step3 loc
#1
display(df.loc[2:8, ['A', 'C']])
#2
display(df.loc[:,['A', 'C']])
#3
display(df.loc[3:8])
#4
display(df.loc[[3]])

          A         C
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717

          A         C
0  0.471435  1.432707
1 -0.720589  0.859588
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717
9  0.124713  0.841675

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118

In [135]:
#Step3 iloc
#1
display(df.iloc[0:7,[0]])
#2
display(df.iloc[:,[0]])
#3
display(df.iloc[2:7])
#4
display(df.iloc[[5]])

          A
0  0.471435
1 -0.720589
2  0.015696
3  0.953324
4  0.405453
5 -0.202646
6  1.318152

          A
0  0.471435
1 -0.720589
2  0.015696
3  0.953324
4  0.405453
5 -0.202646
6  1.318152
7 -0.183109
8  1.047579
9  0.124713

          A         B         C         D
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027

          A         B         C         D
5 -0.202646 -0.655969  0.193421  0.553439

In [136]:
#Step4
#1
display(df.query('D > 0.5'))
#2
display(df.query('B > D'))
#2-2
display(df[df.B > df.D])
#3
display(df.query('A > 0.5 & D < 0.0'))
#4
display(df.query('A > 0.5 | D < 0.0'))

          A         B         C         D
2  0.015696 -2.242685  1.150036  0.991946
5 -0.202646 -0.655969  0.193421  0.553439
9  0.124713 -0.322795  0.841675  2.390961

          A         B         C         D
1 -0.720589  0.887163  0.859588 -0.636524
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

          A         B         C         D
1 -0.720589  0.887163  0.859588 -0.636524
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

          A         B         C         D
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092

          A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092

## 실습 5번

In [137]:
#Step1
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df5 = pd.DataFrame({'E': ['E4', 'E5', 'E6', 'E7'],
                    'F': ['F4', 'F5', 'F6', 'F7'],
                    'G': ['G4', 'G5', 'G6', 'G7'],
                    'H': ['H4', 'H5', 'H6', 'H7']},
                   index=[0, 1, 2, 3])
df6 = pd.DataFrame({'I': ['I8', 'I9', 'I10', 'I11'],
                    'J': ['J8', 'J9', 'J10', 'J11'],
                    'K': ['K8', 'K9', 'K10', 'K11'],
                    'L': ['L8', 'L9', 'L10', 'L11']},
                   index=[0, 1, 2, 3])

In [138]:
#Step2,3
result = pd.concat([df4,df5,df6], axis = 1, join ='inner')
result

    A   B   C   D   E   F   G   H    I    J    K    L
0  A0  B0  C0  D0  E4  F4  G4  H4   I8   J8   K8   L8
1  A1  B1  C1  D1  E5  F5  G5  H5   I9   J9   K9   L9
2  A2  B2  C2  D2  E6  F6  G6  H6  I10  J10  K10  L10
3  A3  B3  C3  D3  E7  F7  G7  H7  I11  J11  K11  L11

## 실습 6번

In [139]:
#Step1
df1 = pd.read_csv("FITNESS_1.csv", encoding = 'cp949')
df2 = pd.read_csv("FITNESS_2.csv", encoding = 'cp949')

In [140]:
#Step2
result = pd.merge(df1,df2, on = ["NAME","GENDER","AGE"], how = 'inner')
result

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185
5,Allen,남성,38,30대,89.02,49.874,9.22,178,55,180
6,Nancy,여성,49,40대,76.32,48.673,9.40,186,56,188
7,Patty,여성,52,50대,76.32,45.441,9.63,164,48,166
8,Suzanne,여성,57,50대,59.08,50.545,9.93,148,49,155
9,Teresa,여성,51,50대,77.91,46.672,10.00,162,48,168
10,Bob,남성,39,30대,75.07,45.313,10.07,185,62,185
11,Harriett,여성,49,40대,73.37,50.388,10.08,168,67,168
12,Jane,여성,44,40대,73.03,50.541,10.13,168,45,168
13,Harold,남성,48,40대,91.63,46.774,10.25,162,48,164
14,Sammy,남성,54,50대,83.12,51.855,10.33,166,50,170
15,Buffy,여성,52,50대,73.71,45.790,10.47,186,59,188
16,Trent,남성,38,30대,82.78,47.467,10.50,170,53,172
17,Jackie,여성,47,40대,79.15,47.273,10.60,162,47,164
18,Ralph,남성,43,40대,81.19,49.091,10.85,162,64,170
19,Jack,남성,51,50대,69.63,40.836,10.95,168,57,172
20,Annie,여성,51,50대,67.25,45.118,11.08,172,48,172
21,Kate,여성,45,40대,66.45,44.754,11.12,176,51,176
22,Carl,남성,54,50대,79.38,46.080,11.17,156,62,165
23,Don,남성,44,40대,89.47,44.609,11.37,178,62,182
24,Effie,여성,48,40대,61.24,47.920,11.50,170,52,176
25,George,남성,37,30대,77.45,44.811,11.63,176,58,176
26,Iris,여성,39,30대,75.98,45.681,11.95,176,70,180
27,Mark,남성,57,50대,73.37,39.407,12.63,174,58,176
28,Steve,남성,54,50대,91.63,39.203,12.88,168,44,172
29,Vaughn,남성,44,40대,81.42,39.442,13.08,174,63,176
30,William,남성,45,40대,87.66,37.388,14.03,186,56,192

In [141]:
#Step1
df3 = pd.read_csv("FITNESS.csv", encoding = 'cp949')
display(df3)

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185
5,Allen,남성,38,30대,89.02,49.874,9.22,178,55,180
6,Nancy,여성,49,40대,76.32,48.673,9.40,186,56,188
7,Patty,여성,52,50대,76.32,45.441,9.63,164,48,166
8,Suzanne,여성,57,50대,59.08,50.545,9.93,148,49,155
9,Teresa,여성,51,50대,77.91,46.672,10.00,162,48,168
10,Bob,남성,39,30대,75.07,45.313,10.07,185,62,185
11,Harriett,여성,49,40대,73.37,50.388,10.08,168,67,168
12,Jane,여성,44,40대,73.03,50.541,10.13,168,45,168
13,Harold,남성,48,40대,91.63,46.774,10.25,162,48,164
14,Sammy,남성,54,50대,83.12,51.855,10.33,166,50,170
15,Buffy,여성,52,50대,73.71,45.790,10.47,186,59,188
16,Trent,남성,38,30대,82.78,47.467,10.50,170,53,172
17,Jackie,여성,47,40대,79.15,47.273,10.60,162,47,164
18,Ralph,남성,43,40대,81.19,49.091,10.85,162,64,170
19,Jack,남성,51,50대,69.63,40.836,10.95,168,57,172
20,Annie,여성,51,50대,67.25,45.118,11.08,172,48,172
21,Kate,여성,45,40대,66.45,44.754,11.12,176,51,176
22,Carl,남성,54,50대,79.38,46.080,11.17,156,62,165
23,Don,남성,44,40대,89.47,44.609,11.37,178,62,182
24,Effie,여성,48,40대,61.24,47.920,11.50,170,52,176
25,George,남성,37,30대,77.45,44.811,11.63,176,58,176
26,Iris,여성,39,30대,75.98,45.681,11.95,176,70,180
27,Mark,남성,57,50대,73.37,39.407,12.63,174,58,176
28,Steve,남성,54,50대,91.63,39.203,12.88,168,44,172
29,Vaughn,남성,44,40대,81.42,39.442,13.08,174,63,176
30,William,남성,45,40대,87.66,37.388,14.03,186,56,192

## 실습 7번

In [142]:
#Step1
df = pd.read_csv("FITNESS.csv", encoding = 'cp949')

In [143]:
#Step2
result = df.groupby(by = ['GENDER','AGEGROUP']).mean(numeric_only=True)['WEIGHT'].reset_index()
display(result)

  GENDER AGEGROUP     WEIGHT
0     남성      30대  81.080000
1     남성      40대  85.465000
2     남성      50대  79.426000
3     여성      30대  78.925000
4     여성      40대  72.943750
5     여성      50대  70.856667

In [144]:
#Step3
pivot_result1 = result.pivot(index = 'GENDER', columns = 'AGEGROUP', values = 'WEIGHT')
pivot_result2 = result.pivot(index = 'AGEGROUP', columns = 'GENDER', values = 'WEIGHT')
display(pivot_result1)
display(pivot_result2)

AGEGROUP     30대       40대        50대
GENDER
남성        81.080  85.46500  79.426000
여성        78.925  72.94375  70.856667

GENDER        남성         여성
AGEGROUP
30대       81.080  78.925000
40대       85.465  72.943750
50대       79.426  70.856667