### Series

In [6]:
import pandas as pd

dict_data = {'a':1, 'b':2, 'c':3}
print(type(dict_data))
sr = pd.Series(dict_data)
display(sr)
print(type(sr))

<class 'dict'>

a    1
b    2
c    3
dtype: int64

<class 'pandas.core.series.Series'>

### Dataframe

In [ ]:
table = {"일자" : ['2019-01-01', '2019-01-04', '2019-01-07', '2019-01-10', '2019-01-13'],
         "가격" :[1000, 1500, 2000, 2500, 3000],
         "구매여부" : ['False', 'True', 'True', 'True', 'True'],
         "제품" : ['gum', 'snack', 'beverage', 'dongas', 'alcohol']}
table
df = pd.DataFrame(table)
display(df)
display(type(df))
print(type(df))

### 실습1

In [255]:
dict_data = {'1':"홍길동", '2':"이순신", '3':"강감찬"}
sr = pd.Series(dict_data)
print(type(sr))
sr

<class 'pandas.core.series.Series'>

1    홍길동
2    이순신
3    강감찬
dtype: object

In [261]:
table = {"성명" : ["홍길동", "이순신", "강감찬", "이성계", "정약용"],
         "국어성적" :[90,95,85,90,95],
         "영어성적" :[90,85,90,95,95],
         "수학성적" :[95,90,85,75,90]}
df = pd.DataFrame(table)
display(df)

    성명  국어성적  영어성적  수학성적
0  홍길동    90    90    95
1  이순신    95    85    90
2  강감찬    85    90    85
3  이성계    90    95    75
4  정약용    95    95    90

### 연습1

In [46]:
import os
os.getcwd()
os.chdir('/home/piai/Desktop/git/1 Big Data 분석 기초')

In [47]:
df = pd.read_csv('/home/piai/Desktop/git/1 Big Data 분석 기초/FITNESS.csv', encoding = 'cp949')
df.head()

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185

In [56]:
df = pd.read_excel('성적처리.xlsx',sheet_name = 'Sheet1')
df.tail()

     반   성명  국어  영어  수학  사회  과학
15  3반  조미료  86  68  97  56  85
16  1반  소행성  62  58  58  62  73
17  1반  유비비  67  94  61  61  52
18  2반  이관우  91  65  57  79  93
19  2반  장비비  52  82  93  81  75

### 실습2

In [63]:
df = pd.read_csv('/home/piai/Desktop/git/1 Big Data 분석 기초/성적.csv', encoding = 'cp949')
print(df)4
df.to_excel('/home/piai/Desktop/git/1 Big Data 분석 기초/성적사본.xlsx', encoding = 'cp949', index = False)

   Unnamed: 0   성명  국어성적  영어성적  수학성적
0           0  홍길동    90    90    95
1           1  이순신    95    85    90
2           2  강감찬    85    90    85
3           3  이성계    90    95    75
4           4  정약용    95    95    90

/home/piai/anaconda3/lib/python3.10/site-packages/pandas/util/_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)

### 데이터 내용 확인

In [157]:
df = pd.read_csv('auto_mpg.csv')
print(f"{df.shape}\n")
df.mpg.dtypes

(398, 9)

dtype('float64')

In [158]:
df.origin.nunique(), df.origin.unique()

(3, array([1, 3, 2]))

In [159]:
df.groupby(by = 'cylinders').mean(numeric_only=True)

,mpg,displacement,weight,acceleration,modelyear,origin
cylinders,,,,,,
3,20.550000,72.500000,2398.500000,13.250000,75.500000,3.000000
4,29.286765,109.796569,2308.127451,16.601471,77.073529,1.985294
5,27.366667,145.000000,3103.333333,18.633333,79.000000,2.000000
6,19.985714,218.142857,3198.226190,16.263095,75.928571,1.190476
8,14.963107,345.009709,4114.718447,12.955340,73.902913,1.000000

In [165]:
df.select_dtypes(include = 'number').groupby(by = ['modelyear', 'cylinders']).agg(['mean', 'median'])['mpg']

                          mean  median
modelyear cylinders
70        4          25.285714   25.00
          6          20.500000   21.00
          8          14.111111   14.50
71        4          27.461538   27.00
          6          18.000000   18.00
          8          13.428571   14.00
72        3          19.000000   19.00
          4          23.428571   23.00
          8          13.615385   13.00
73        3          18.000000   18.00
          4          22.727273   22.00
          6          19.000000   18.00
          8          13.200000   13.00
74        4          27.800000   26.00
          6          17.857143   18.00
          8          14.200000   14.00
75        4          25.250000   24.00
          6          17.583333   18.00
          8          15.666667   15.50
76        4          26.766667   27.00
          6          20.000000   19.50
          8          14.666667   14.50
77        3          21.500000   21.50
          4          29.107143   30.00
          6          19.500000   19.00
          8          16.000000   15.75
78        4          29.576471   29.50
          5          20.300000   20.30
          6          19.066667   19.30
          8          19.050000   19.30
79        4          31.525000   32.70
          5          25.400000   25.40
          6          22.950000   21.05
          8          18.630000   17.90
80        3          23.700000   23.70
          4          34.612000   33.80
          5          36.400000   36.40
          6          25.900000   25.90
81        4          32.814286   33.00
          6          23.428571   23.50
          8          26.600000   26.60
82        4          32.071429   32.00
          6          28.333333   25.00

### 실습3

In [265]:
import os
os.chdir('/home/piai/Desktop/git/1 Big Data 분석 기초')
df = pd.read_csv('FITNESS.csv', encoding = 'cp949')
display(df.head())
display(df.describe())
display(df.groupby(by = 'GENDER').agg(['mean', 'median']))

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185

,AGE,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,46.838710,77.444516,47.375806,10.586129,169.645161,53.451613,173.774194
std,5.860016,8.328568,5.327231,1.387414,10.251986,7.619443,9.164095
min,37.000000,59.080000,37.388000,8.170000,146.000000,40.000000,155.000000
25%,43.000000,73.200000,44.964500,9.780000,163.000000,48.000000,168.000000
50%,48.000000,77.450000,46.774000,10.470000,170.000000,52.000000,172.000000
75%,51.000000,82.325000,50.131000,11.270000,176.000000,58.500000,180.000000
max,57.000000,91.630000,60.055000,14.030000,186.000000,70.000000,192.000000

/tmp/ipykernel_152686/1248113144.py:6: FutureWarning: ['NAME', 'AGEGROUP'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  display(df.groupby(by = 'GENDER').agg(['mean', 'median']))

              AGE            WEIGHT               OXY            RUNTIME  \
             mean median       mean median       mean   median      mean
GENDER
남성      46.333333   45.0  82.282667  81.42  44.753733  45.3130  11.19400
여성      47.312500   48.5  72.908750  73.54  49.834000  48.2965  10.01625

              RUNPULSE          RSTPULSE        MAXPULSE
       median     mean median       mean median     mean median
GENDER
남성      10.95   172.20  174.0  55.733333   57.0  175.800  176.0
여성      10.04   167.25  168.0  51.312500   48.0  171.875  170.0

In [174]:
df.groupby(by = 'GENDER').agg(['mean', 'median'])

/tmp/ipykernel_152686/2779982026.py:1: FutureWarning: ['NAME', 'AGEGROUP'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby(by = 'GENDER').agg(['mean', 'median'])

              AGE            WEIGHT               OXY            RUNTIME  \
             mean median       mean median       mean   median      mean
GENDER
남성      46.333333   45.0  82.282667  81.42  44.753733  45.3130  11.19400
여성      47.312500   48.5  72.908750  73.54  49.834000  48.2965  10.01625

              RUNPULSE          RSTPULSE        MAXPULSE
       median     mean median       mean median     mean median
GENDER
남성      10.95   172.20  174.0  55.733333   57.0  175.800  176.0
여성      10.04   167.25  168.0  51.312500   48.0  171.875  170.0

### 데이터 선택

In [193]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [197]:
np.random.seed(1234)
df = pd.DataFrame(randn(10,2),columns = ['A','B'])
df

          A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092
9  1.321158 -1.546906

In [204]:
print(type(df['A']))
print(type(df[['A']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [221]:
df[['A'][0:4]]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [222]:
df.loc[0:4,['A']]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696

In [225]:
df.iloc[0:8,[0]]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077

In [234]:
df.iloc[1:2,[0:1]]

SyntaxError: invalid syntax (2809701257.py, line 1)

In [229]:
df[df.A < df.B]

          A         B
2 -0.720589  0.887163
7 -0.334077  0.002118

In [235]:
df.query('A > 0.5 | B < 0.0')

          A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
9  1.321158 -1.546906

In [236]:
# 38 Page (데이터선택 연습)
df = pd.DataFrame({'ABC': ['A','B','C','A'], 
                   'abc':['a','b','c','c'],
                   'group1':['G1','G2','G3','G4'],
                   'value1':[11,13,12,14],
                   'val1_mod':[0.231,0.197,0.213, 0.199] })
df

  ABC abc group1  value1  val1_mod
0   A   a     G1      11     0.231
1   B   b     G2      13     0.197
2   C   c     G3      12     0.213
3   A   c     G4      14     0.199

In [239]:
df.filter(items = ['group1','value1'])

  group1  value1
0     G1      11
1     G2      13
2     G3      12
3     G4      14

In [243]:
df.filter(regex = '1',axis=1)

  group1  value1  val1_mod
0     G1      11     0.231
1     G2      13     0.197
2     G3      12     0.213
3     G4      14     0.199

In [244]:
df.filter(regex = '1$',axis=1)

  group1  value1
0     G1      11
1     G2      13
2     G3      12
3     G4      14

In [245]:
df.filter(like = 'a', axis =1)

  abc  value1  val1_mod
0   a      11     0.231
1   b      13     0.197
2   c      12     0.213
3   c      14     0.199

In [247]:
df.filter(regex = '[Aa]', axis =1)

  ABC abc  value1  val1_mod
0   A   a      11     0.231
1   B   b      13     0.197
2   C   c      12     0.213
3   A   c      14     0.199

In [250]:
display(df)
df.mask(df.value1>12, other = 999)

  ABC abc group1  value1  val1_mod
0   A   a     G1      11     0.231
1   B   b     G2      13     0.197
2   C   c     G3      12     0.213
3   A   c     G4      14     0.199

   ABC  abc group1  value1  val1_mod
0    A    a     G1      11     0.231
1  999  999    999     999   999.000
2    C    c     G3      12     0.213
3  999  999    999     999   999.000

In [251]:
df.mask(df.abc == 'a')

   ABC  abc group1  value1  val1_mod
0  NaN  NaN    NaN     NaN       NaN
1    B    b     G2    13.0     0.197
2    C    c     G3    12.0     0.213
3    A    c     G4    14.0     0.199

### 실습 4번

In [278]:
import numpy as np
from numpy.random import randn
np.random.seed(1234)
df = pd.DataFrame(randn(10,4),columns = ['A','B','C','D'])

In [279]:
display(df[['B']])
display(df[['B','D']])
display(df[4:9])

          B
0 -1.190976
1  0.887163
2 -2.242685
3 -2.021255
4  0.289092
5 -0.655969
6 -0.469305
7  1.058969
8  1.045938
9 -0.322795

          B         D
0 -1.190976 -0.312652
1  0.887163 -0.636524
2 -2.242685  0.991946
3 -2.021255  0.002118
4  0.289092 -1.546906
5 -0.655969  0.553439
6 -0.469305 -1.817027
7  1.058969  0.337438
8  1.045938 -0.122092
9 -0.322795  2.390961

          A         B         C         D
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [306]:
display(df.loc[2:8, ['A', 'C']])
display(df.loc[:,['A', 'C']])
display(df.loc[3:8])
display(df.loc[[3]])

          A         C
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717

          A         C
0  0.471435  1.432707
1 -0.720589  0.859588
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717
9  0.124713  0.841675

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118

### conacat, append

In [322]:
# df1, df2, df3 데이터 생성
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

In [323]:
result = pd.concat([df1,df2,df3])
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [328]:
result = pd.concat([df1,df2,df3], axis = 1, ignore_index = True)
result

     0    1    2    3    4    5    6    7    8    9    10   11
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [332]:
result.columns = ["col_"+str(i) for i in range(12)]
result

   col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11
0     A0    B0    C0    D0   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
1     A1    B1    C1    D1   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
2     A2    B2    C2    D2   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
3     A3    B3    C3    D3   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
4    NaN   NaN   NaN   NaN    A4    B4    C4    D4   NaN   NaN    NaN    NaN
5    NaN   NaN   NaN   NaN    A5    B5    C5    D5   NaN   NaN    NaN    NaN
6    NaN   NaN   NaN   NaN    A6    B6    C6    D6   NaN   NaN    NaN    NaN
7    NaN   NaN   NaN   NaN    A7    B7    C7    D7   NaN   NaN    NaN    NaN
8    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    A8    B8     C8     D8
9    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    A9    B9     C9     D9
10   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   A10   B10    C10    D10
11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   A11   B11    C11    D11

### 실습5

In [325]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df5 = pd.DataFrame({'E': ['E4', 'E5', 'E6', 'E7'],
                    'F': ['F4', 'F5', 'F6', 'F7'],
                    'G': ['G4', 'G5', 'G6', 'G7'],
                    'H': ['H4', 'H5', 'H6', 'H7']},
                   index=[0, 1, 2, 3])
df6 = pd.DataFrame({'I': ['I8', 'I9', 'I10', 'I11'],
                    'J': ['J8', 'J9', 'J10', 'J11'],
                    'K': ['K8', 'K9', 'K10', 'K11'],
                    'L': ['L8', 'L9', 'L10', 'L11']},
                   index=[0, 1, 2, 3])

In [333]:
result = pd.concat([df4,df5,df6], axis = 1, join ='inner')
result

    A   B   C   D   E   F   G   H    I    J    K    L
0  A0  B0  C0  D0  E4  F4  G4  H4   I8   J8   K8   L8
1  A1  B1  C1  D1  E5  F5  G5  H5   I9   J9   K9   L9
2  A2  B2  C2  D2  E6  F6  G6  H6  I10  J10  K10  L10
3  A3  B3  C3  D3  E7  F7  G7  H7  I11  J11  K11  L11

### merge, join

In [334]:
# 53 Page (데이터결합 연습)
# left, right 데이터 생성
left = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [340]:
result = pd.merge(left, right, on = ['key1','key2'])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K2   K0  A2  B2  C2  D2

In [345]:
result = pd.merge(left, right, on = ['key1','key2'], how = 'outer')
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K1   K1   A1   B1  NaN  NaN
2   K2   K0   A2   B2   C2   D2
3   K3   K1   A3   B3  NaN  NaN
4   K1   K0  NaN  NaN   C1   D1
5   K3   K0  NaN  NaN   C3   D3

In [350]:
result = pd.merge(left, right, on = ['key1','key2'], how = 'outer', indicator = True)
result

  key1 key2    A    B    C    D      _merge
0   K0   K0   A0   B0   C0   D0        both
1   K1   K1   A1   B1  NaN  NaN   left_only
2   K2   K0   A2   B2   C2   D2        both
3   K3   K1   A3   B3  NaN  NaN   left_only
4   K1   K0  NaN  NaN   C1   D1  right_only
5   K3   K0  NaN  NaN   C3   D3  right_only

In [351]:
# 57 Page (데이터결합 연습)
# left, right 데이터 생성
left = pd.DataFrame({'key1': [1, 2, 3, 4],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'C': ['C1', 'C2', 'C5'],
                      'D': ['D1', 'D2', 'D5']},
                     index=[1, 2, 5])

In [359]:
result = left.join(right, how = 'inner')
result

   key1   A   B   C   D
1     2  A1  B1  C1  D1
2     3  A2  B2  C2  D2

In [361]:
result = left.join(right, how = 'right')
result

   key1    A    B   C   D
1   2.0   A1   B1  C1  D1
2   3.0   A2   B2  C2  D2
5   NaN  NaN  NaN  C5  D5

### 실습6

In [364]:
df1 = pd.read_csv("FITNESS_1.csv", encoding = 'cp949')
df2 = pd.read_csv("FITNESS_2.csv", encoding = 'cp949')

In [366]:
display(df1.head())
display(df2.head())

     NAME GENDER  AGE AGEGROUP  WEIGHT
0   Donna     여성   42      40대   68.15
1  Gracie     여성   38      30대   81.87
2  Luanne     여성   43      40대   85.84
3    Mimi     여성   50      50대   70.87
4   Chris     남성   49      40대   81.42

     NAME GENDER  AGE     OXY  RUNTIME  RUNPULSE  RSTPULSE  MAXPULSE
0   Donna     여성   42  59.571     8.17       166        40       172
1  Gracie     여성   38  60.055     8.63       170        48       186
2  Luanne     여성   43  54.297     8.65       156        45       168
3    Mimi     여성   50  54.625     8.92       146        48       155
4   Chris     남성   49  49.156     8.95       180        44       185

In [370]:
result = pd.merge(df1,df2, on = ["NAME","GENDER","AGE"], how = 'inner')
result

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185
5,Allen,남성,38,30대,89.02,49.874,9.22,178,55,180
6,Nancy,여성,49,40대,76.32,48.673,9.40,186,56,188
7,Patty,여성,52,50대,76.32,45.441,9.63,164,48,166
8,Suzanne,여성,57,50대,59.08,50.545,9.93,148,49,155
9,Teresa,여성,51,50대,77.91,46.672,10.00,162,48,168
10,Bob,남성,39,30대,75.07,45.313,10.07,185,62,185
11,Harriett,여성,49,40대,73.37,50.388,10.08,168,67,168
12,Jane,여성,44,40대,73.03,50.541,10.13,168,45,168
13,Harold,남성,48,40대,91.63,46.774,10.25,162,48,164
14,Sammy,남성,54,50대,83.12,51.855,10.33,166,50,170
15,Buffy,여성,52,50대,73.71,45.790,10.47,186,59,188
16,Trent,남성,38,30대,82.78,47.467,10.50,170,53,172
17,Jackie,여성,47,40대,79.15,47.273,10.60,162,47,164
18,Ralph,남성,43,40대,81.19,49.091,10.85,162,64,170
19,Jack,남성,51,50대,69.63,40.836,10.95,168,57,172
20,Annie,여성,51,50대,67.25,45.118,11.08,172,48,172
21,Kate,여성,45,40대,66.45,44.754,11.12,176,51,176
22,Carl,남성,54,50대,79.38,46.080,11.17,156,62,165
23,Don,남성,44,40대,89.47,44.609,11.37,178,62,182
24,Effie,여성,48,40대,61.24,47.920,11.50,170,52,176
25,George,남성,37,30대,77.45,44.811,11.63,176,58,176
26,Iris,여성,39,30대,75.98,45.681,11.95,176,70,180
27,Mark,남성,57,50대,73.37,39.407,12.63,174,58,176
28,Steve,남성,54,50대,91.63,39.203,12.88,168,44,172
29,Vaughn,남성,44,40대,81.42,39.442,13.08,174,63,176
30,William,남성,45,40대,87.66,37.388,14.03,186,56,192

### Transpose, pivot, melt

In [11]:
# 67 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'index': [1,1,1,2,2,2],
                   'column': ['col_1', 'col_2', 'col_3', 'col_1', 'col_2', 'col_3'],
                   'value_1': [1, 2, 3, 4, 5, 6],
                   'value_2': ['x', 'y', 'z', 'q', 'w', 't']})
df

   index column  value_1 value_2
0      1  col_1        1       x
1      1  col_2        2       y
2      1  col_3        3       z
3      2  col_1        4       q
4      2  col_2        5       w
5      2  col_3        6       t

In [12]:
display(df.T)

             0      1      2      3      4      5
index        1      1      1      2      2      2
column   col_1  col_2  col_3  col_1  col_2  col_3
value_1      1      2      3      4      5      6
value_2      x      y      z      q      w      t

In [15]:
df.pivot(index = 'index', columns = 'column', values = 'value_1')

column  col_1  col_2  col_3
index
1           1      2      3
2           4      5      6

In [16]:
df.pivot(index = 'index', columns = 'column', values = ['value_1','value_2'])

       value_1             value_2
column   col_1 col_2 col_3   col_1 col_2 col_3
index
1            1     2     3       x     y     z
2            4     5     6       q     w     t

### 실습7

In [72]:
import os
os.chdir('/home/piai/Desktop/git/1 Big Data 분석 기초')
df = pd.read_csv("FITNESS.csv", encoding = 'cp949')
result = df.groupby(by = ['GENDER','AGEGROUP']).mean(numeric_only=True).reset_index()
pivot_result1 = result.pivot(index = 'GENDER', columns = 'AGEGROUP', values = 'WEIGHT')
pivot_result2 = result.pivot(index = 'AGEGROUP', columns = 'GENDER', values = 'WEIGHT')
display(pivot_result1)
display(pivot_result2)

AGEGROUP     30대       40대        50대
GENDER
남성        81.080  85.46500  79.426000
여성        78.925  72.94375  70.856667

GENDER        남성         여성
AGEGROUP
30대       81.080  78.925000
40대       85.465  72.943750
50대       79.426  70.856667

### Stack, Unstack

In [73]:
# 74 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'index': [1,2,3],
                   'alpha': ['A', 'B', 'C'],
                   'values': [11, 22, 33],
                   'xyz': ['x', 'y', 'z']})
df

   index alpha  values xyz
0      1     A      11   x
1      2     B      22   y
2      3     C      33   z

In [74]:
df_stack = df.stack(level = -1)
print("stack 데이터 크기: ", df_stack.shape) # (12,) 배열
df_stack

stack 데이터 크기:  (12,)

0  index      1
   alpha      A
   values    11
   xyz        x
1  index      2
   alpha      B
   values    22
   xyz        y
2  index      3
   alpha      C
   values    33
   xyz        z
dtype: object

In [75]:
df_unstack = df_stack.unstack()
df_unstack

  index alpha values xyz
0     1     A     11   x
1     2     B     22   y
2     3     C     33   z

In [76]:
# 79 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'factor1': ['A', 'A', 'A', 'A', 'A','B','B','B', 'B'],
                   'factor2':['a','b','c','a','b','a','b', 'c','c'],
                   'value':[11,13,12,12,14,12,13,11,12]})
df

  factor1 factor2  value
0       A       a     11
1       A       b     13
2       A       c     12
3       A       a     12
4       A       b     14
5       B       a     12
6       B       b     13
7       B       c     11
8       B       c     12

In [79]:
pd.crosstab(df.factor1,df.factor2, rownames = ['Fact1'], colnames = ['Fact2'], margins = True)
# Margin은 total값

Fact2  a  b  c  All
Fact1
A      2  2  1    5
B      1  1  2    4
All    3  3  3    9

In [82]:
pd.crosstab(df.factor1,[df.factor2, df.value])

factor2  a     b     c
value   11 12 13 14 11 12
factor1
A        1  1  1  1  0  1
B        0  1  1  0  1  1

In [84]:
pd.crosstab([df.factor1,df.factor2], df.value, normalize = True)

value                  11        12        13        14
factor1 factor2
A       a        0.111111  0.111111  0.000000  0.000000
        b        0.000000  0.000000  0.111111  0.111111
        c        0.000000  0.111111  0.000000  0.000000
B       a        0.000000  0.111111  0.000000  0.000000
        b        0.000000  0.000000  0.111111  0.000000
        c        0.111111  0.111111  0.000000  0.000000

In [90]:
# 83 Page (데이터변환 연습)
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [95]:
df_sort = df.sort_values(by='c1',ascending = False)
df_sort

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [103]:
# 86 Page (데이터중복확인 연습)
# 데이터 불러오기
df = pd.read_excel('판매실적_이해.xlsx', sheet_name = 'Sheet1')
df = df.dropna()
df

    지역   제품  판매수   판매액
0   동부   TV    1  1000
1   남부   TV    1  1000
2   서부  냉장고    1  2000
3   동부  세탁기    1  1000
4   북부  세탁기    1  1000
5   동부  냉장고    2  4000
6   남부  냉장고    1  2000
7   서부  세탁기    1  1000
8   동부   TV    1  1000
9   남부  냉장고    1  2000
10  서부   TV    1  1000
11  남부  세탁기    1  1000

In [104]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10    False
11    False
dtype: bool

In [105]:
df[df.duplicated()]

   지역   제품  판매수   판매액
8  동부   TV    1  1000
9  남부  냉장고    1  2000

In [107]:
df.drop_duplicates(ignore_index=False)

    지역   제품  판매수   판매액
0   동부   TV    1  1000
1   남부   TV    1  1000
2   서부  냉장고    1  2000
3   동부  세탁기    1  1000
4   북부  세탁기    1  1000
5   동부  냉장고    2  4000
6   남부  냉장고    1  2000
7   서부  세탁기    1  1000
10  서부   TV    1  1000
11  남부  세탁기    1  1000

In [125]:
import numpy as np
import pandas as pd
pop_seoul = pd.read_csv("서울인구통계.txt", sep = "\t", thousands = ',', skiprows = 2, encoding = 'utf-8')
pop_seoul.head()

,기간,자치구,세대,계,남자,여자,계.1,남자.1,여자.1,계.2,남자.2,여자.2,세대당인구,65세이상고령자
0,2021.3/4,합계,4421143,9765869,4739972,5025897,9542256,4636069,4906187,223613,103903,119710,2.16,1592339
1,2021.3/4,종로구,73652,154318,74561,79757,145512,70666,74846,8806,3895,4911,1.98,27776
2,2021.3/4,중구,63267,131943,64274,67669,122858,59853,63005,9085,4421,4664,1.94,24225
3,2021.3/4,용산구,111177,238300,115655,122645,224145,107801,116344,14155,7854,6301,2.02,38906
4,2021.3/4,성동구,134620,294140,143055,151085,287820,140290,147530,6320,2765,3555,2.14,46053

In [126]:
pop1 = pop_seoul[['자치구', '계', '계.1', '계.2', '65세이상고령자']]
pop_seoul=pop1.drop([0])
pop_seoul.head()

   자치구       계     계.1    계.2  65세이상고령자
1  종로구  154318  145512   8806     27776
2   중구  131943  122858   9085     24225
3  용산구  238300  224145  14155     38906
4  성동구  294140  287820   6320     46053
5  광진구  353380  341112  12268     51278

In [128]:
pop_seoul.rename(columns = {pop_seoul.columns[0]:'구별',
                            pop_seoul.columns[1]:'인구수',
                            pop_seoul.columns[2]:'한국인',
                            pop_seoul.columns[3]:'외국인',
                            pop_seoul.columns[4]:'고령자'}, inplace = True)
pop_seoul.head()

    구별     인구수     한국인    외국인    고령자
1  종로구  154318  145512   8806  27776
2   중구  131943  122858   9085  24225
3  용산구  238300  224145  14155  38906
4  성동구  294140  287820   6320  46053
5  광진구  353380  341112  12268  51278

In [146]:
cctv_seoul = pd.read_excel("서울시CCTV.xlsx", skiprows= 2, names= ['기관명', '소계', '2011년 이전', \
 '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년', '2019년', '2020년', '2021년'])
cctv_seoul.head()

,기관명,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32

In [147]:
cctv_seoul.rename(columns = {cctv_seoul.columns[0]: '구별'}, inplace = True)
cctv_seoul.rename(columns = {cctv_seoul.columns[1]: 'cctv수'}, inplace = True)
cctv_seoul.head()

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32

In [148]:
cctv_seoul.sort_values(by = 'cctv수', ascending= True)

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
19,동작구,2297,41,24,25,503,128,253,271,300,322,419,11
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
17,금천구,2374,0,0,178,80,361,133,196,540,369,508,9
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
10,노원구,2415,0,97,193,77,516,331,175,216,320,386,104
13,마포구,2421,58,93,77,61,162,454,359,343,494,300,20
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39
5,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63
24,강동구,2547,332,27,163,49,154,202,273,377,356,614,0
15,강서구,2560,55,129,106,213,188,168,506,259,457,356,123
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32
23,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101
12,서대문구,2940,730,253,155,108,137,223,356,237,343,397,1
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4
14,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
21,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3
18,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131
7,성북구,3958,83,78,170,230,323,594,460,867,714,251,188
16,구로구,4075,852,216,349,187,268,326,540,488,434,415,0
20,관악구,4942,428,205,291,513,529,621,687,663,640,331,34
22,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1

In [149]:
cctv_seoul['최근증가율']=(cctv_seoul['2021년']+cctv_seoul['2020년']+cctv_seoul['2019년']) \
   /(cctv_seoul['cctv수']-(cctv_seoul['2021년']+cctv_seoul['2020년']+cctv_seoul['2019년']))*100
cctv_seoul.sort_values(by='최근증가율',ascending=False).head(5)

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39,194.850299
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4,152.760736
23,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101,96.827586
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331,74.785408
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131,63.758099

In [152]:
pop_seoul['외국인 비율'] = pop_seoul['외국인']/pop_seoul['인구수']*100
pop_seoul['고령자 비율'] = pop_seoul['고령자']/pop_seoul['인구수']*100
pop_seoul.head()

    구별     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
1  종로구  154318  145512   8806  27776  5.706398  17.999196
2   중구  131943  122858   9085  24225  6.885549  18.360201
3  용산구  238300  224145  14155  38906  5.939992  16.326479
4  성동구  294140  287820   6320  46053  2.148637  15.656830
5  광진구  353380  341112  12268  51278  3.471617  14.510725

In [156]:
pop_seoul.sort_values(by = '외국인 비율')

      구별     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
10   도봉구  320711  318718   1993  63448  0.621432  19.783543
15   양천구  452255  449010   3245  67880  0.717516  15.009232
11   노원구  517038  513053   3985  87537  0.770736  16.930477
12   은평구  477961  474062   3899  86724  0.815757  18.144577
25   강동구  467997  464163   3834  73228  0.819236  15.647109
24   송파구  664996  659385   5611  96453  0.843764  14.504298
23   강남구  538075  533359   4716  77222  0.876458  14.351531
22   서초구  420045  416285   3760  60493  0.895142  14.401552
16   강서구  581265  575875   5390  91505  0.927288  15.742389
9    강북구  304257  300887   3370  63914  1.107616  21.006583
7    중랑구  393149  388554   4595  70908  1.168768  18.035910
8    성북구  441717  432628   9089  74235  2.057652  16.806009
4    성동구  294140  287820   6320  46053  2.148637  15.656830
20   동작구  396122  387117   9005  66306  2.273290  16.738782
14   마포구  379525  369903   9622  54260  2.535274  14.296818
21   관악구  501572  488029  13543  79444  2.700111  15.839002
13  서대문구  316415  306249  10166  54056  3.212869  17.083893
5    광진구  353380  341112  12268  51278  3.471617  14.510725
6   동대문구  351626  337846  13780  61759  3.918937  17.563832
1    종로구  154318  145512   8806  27776  5.706398  17.999196
18   금천구  244887  230644  14243  40691  5.816152  16.616235
17   구로구  422361  397506  24855  71930  5.884776  17.030455
3    용산구  238300  224145  14155  38906  5.939992  16.326479
19  영등포구  401814  377536  24278  62108  6.042099  15.456903
2     중구  131943  122858   9085  24225  6.885549  18.360201

In [158]:
pop_seoul.sort_values(by = '고령자 비율')

      구별     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
14   마포구  379525  369903   9622  54260  2.535274  14.296818
23   강남구  538075  533359   4716  77222  0.876458  14.351531
22   서초구  420045  416285   3760  60493  0.895142  14.401552
24   송파구  664996  659385   5611  96453  0.843764  14.504298
5    광진구  353380  341112  12268  51278  3.471617  14.510725
15   양천구  452255  449010   3245  67880  0.717516  15.009232
19  영등포구  401814  377536  24278  62108  6.042099  15.456903
25   강동구  467997  464163   3834  73228  0.819236  15.647109
4    성동구  294140  287820   6320  46053  2.148637  15.656830
16   강서구  581265  575875   5390  91505  0.927288  15.742389
21   관악구  501572  488029  13543  79444  2.700111  15.839002
3    용산구  238300  224145  14155  38906  5.939992  16.326479
18   금천구  244887  230644  14243  40691  5.816152  16.616235
20   동작구  396122  387117   9005  66306  2.273290  16.738782
8    성북구  441717  432628   9089  74235  2.057652  16.806009
11   노원구  517038  513053   3985  87537  0.770736  16.930477
17   구로구  422361  397506  24855  71930  5.884776  17.030455
13  서대문구  316415  306249  10166  54056  3.212869  17.083893
6   동대문구  351626  337846  13780  61759  3.918937  17.563832
1    종로구  154318  145512   8806  27776  5.706398  17.999196
7    중랑구  393149  388554   4595  70908  1.168768  18.035910
12   은평구  477961  474062   3899  86724  0.815757  18.144577
2     중구  131943  122858   9085  24225  6.885549  18.360201
10   도봉구  320711  318718   1993  63448  0.621432  19.783543
9    강북구  304257  300887   3370  63914  1.107616  21.006583

In [160]:
cctv_seoul['구별'] = cctv_seoul['구별'].str.replace(' ','')
result = pd.merge(cctv_seoul, pop_seoul, on= '구별')
result

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율,인구수,한국인,외국인,고령자,외국인 비율,고령자 비율
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43,16.578947,154318,145512,8806,27776,5.706398,17.999196
1,중구,2333,16,114,87,77,236,240,372,386,155,361,289,52.683246,131943,122858,9085,24225,6.885549,18.360201
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0,63.331049,238300,224145,14155,38906,5.939992,16.326479
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76,28.505173,294140,287820,6320,46053,2.148637,15.656830
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32,55.062912,353380,341112,12268,51278,3.471617,14.510725
5,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63,24.725275,351626,337846,13780,61759,3.918937,17.563832
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4,152.760736,393149,388554,4595,70908,1.168768,18.035910
7,성북구,3958,83,78,170,230,323,594,460,867,714,251,188,41.105169,441717,432628,9089,74235,2.057652,16.806009
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39,194.850299,304257,300887,3370,63914,1.107616,21.006583
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331,74.785408,320711,318718,1993,63448,0.621432,19.783543
10,노원구,2415,0,97,193,77,516,331,175,216,320,386,104,50.467290,517038,513053,3985,87537,0.770736,16.930477
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131,63.758099,477961,474062,3899,86724,0.815757,18.144577
12,서대문구,2940,730,253,155,108,137,223,356,237,343,397,1,33.697135,316415,306249,10166,54056,3.212869,17.083893
13,마포구,2421,58,93,77,61,162,454,359,343,494,300,20,50.653391,379525,369903,9622,54260,2.535274,14.296818
14,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0,22.078879,452255,449010,3245,67880,0.717516,15.009232
15,강서구,2560,55,129,106,213,188,168,506,259,457,356,123,57.635468,581265,575875,5390,91505,0.927288,15.742389
16,구로구,4075,852,216,349,187,268,326,540,488,434,415,0,26.317421,422361,397506,24855,71930,5.884776,17.030455
17,금천구,2374,0,0,178,80,361,133,196,540,369,508,9,59.543011,244887,230644,14243,40691,5.816152,16.616235
18,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5,51.422846,401814,377536,24278,62108,6.042099,15.456903
19,동작구,2297,41,24,25,503,128,253,271,300,322,419,11,48.673139,396122,387117,9005,66306,2.273290,16.738782
20,관악구,4942,428,205,291,513,529,621,687,663,640,331,34,25.527051,501572,488029,13543,79444,2.700111,15.839002
21,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3,26.719124,420045,416285,3760,60493,0.895142,14.401552
22,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1,36.310273,538075,533359,4716,77222,0.876458,14.351531
23,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101,96.827586,664996,659385,5611,96453,0.843764,14.504298
24,강동구,2547,332,27,163,49,154,202,273,377,356,614,0,61.509195,467997,464163,3834,73228,0.819236,15.647109

In [164]:
del result['2011년 이전']
del result['2012년']
del result['2013년']
del result['2014년']
del result['2015년']
del result['2016년']
del result['2017년']
del result['2018년']
del result['2019년']
del result['2020년']
del result['2021년']

KeyError: '2011년 이전'

In [165]:
result

      구별  cctv수       최근증가율     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
0    종로구   1772   16.578947  154318  145512   8806  27776  5.706398  17.999196
1     중구   2333   52.683246  131943  122858   9085  24225  6.885549  18.360201
2    용산구   2383   63.331049  238300  224145  14155  38906  5.939992  16.326479
3    성동구   3602   28.505173  294140  287820   6320  46053  2.148637  15.656830
4    광진구   2588   55.062912  353380  341112  12268  51278  3.471617  14.510725
5   동대문구   2497   24.725275  351626  337846  13780  61759  3.918937  17.563832
6    중랑구   3296  152.760736  393149  388554   4595  70908  1.168768  18.035910
7    성북구   3958   41.105169  441717  432628   9089  74235  2.057652  16.806009
8    강북구   2462  194.850299  304257  300887   3370  63914  1.107616  21.006583
9    도봉구   1629   74.785408  320711  318718   1993  63448  0.621432  19.783543
10   노원구   2415   50.467290  517038  513053   3985  87537  0.770736  16.930477
11   은평구   3791   63.758099  477961  474062   3899  86724  0.815757  18.144577
12  서대문구   2940   33.697135  316415  306249  10166  54056  3.212869  17.083893
13   마포구   2421   50.653391  379525  369903   9622  54260  2.535274  14.296818
14   양천구   3312   22.078879  452255  449010   3245  67880  0.717516  15.009232
15   강서구   2560   57.635468  581265  575875   5390  91505  0.927288  15.742389
16   구로구   4075   26.317421  422361  397506  24855  71930  5.884776  17.030455
17   금천구   2374   59.543011  244887  230644  14243  40691  5.816152  16.616235
18  영등포구   3778   51.422846  401814  377536  24278  62108  6.042099  15.456903
19   동작구   2297   48.673139  396122  387117   9005  66306  2.273290  16.738782
20   관악구   4942   25.527051  501572  488029  13543  79444  2.700111  15.839002
21   서초구   3704   26.719124  420045  416285   3760  60493  0.895142  14.401552
22   강남구   6502   36.310273  538075  533359   4716  77222  0.876458  14.351531
23   송파구   2854   96.827586  664996  659385   5611  96453  0.843764  14.504298
24   강동구   2547   61.509195  467997  464163   3834  73228  0.819236  15.647109